//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Animate32 {
            get {
                object obj = ResourceManager.GetObject("Animate32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animating. Press Space to pause or Esc or Enter to exit..
        /// </summary>
        internal static string AnimatingMessage {
            get {
                return ResourceManager.GetString("AnimatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate the selected tool path..
        /// </summary>
        internal static string AnimationToolButtonHint {
            get {
                return ResourceManager.GetString("AnimationToolButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate.
        /// </summary>
        internal static string AnimationToolButtonText {
            get {
                return ResourceManager.GetString("AnimationToolButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At time {0:F2}/{1:F2} ({2:F2}%)..
        /// </summary>
        internal static string AnimationToolMesage {
            get {
                return ResourceManager.GetString("AnimationToolMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///  &lt;panel&gt;
        ///    &lt;group id=&quot;AnimationToolGroup&quot; label=&quot;Profile Options&quot;&gt;
        ///      &lt;container id=&quot;AnimationToolContainer&quot; layoutOrientation=&quot;vertical&quot;&gt;
        ///        &lt;container id=&quot;AnimationToolTransportContainer&quot; layoutOrientation=&quot;horizontal&quot; resizeItemsToFit=&quot;true&quot; isGroup=&quot;1&quot; &gt;
        ///          &lt;button id=&quot;AnimationToolJumpToStartButton&quot; command=&quot;AnimationToolJumpToStartButton&quot; /&gt;
        ///          &lt;button id=&quot;AnimationToolReve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnimationToolOptions {
            get {
                return ResourceManager.GetString("AnimationToolOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string AnimationToolPause {
            get {
                return ResourceManager.GetString("AnimationToolPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string AnimationToolPlay {
            get {
                return ResourceManager.GetString("AnimationToolPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: {0:F2} min.
        /// </summary>
        internal static string AnimationToolPositionLabel {
            get {
                return ResourceManager.GetString("AnimationToolPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed: {0:F2}x.
        /// </summary>
        internal static string AnimationToolSpeedLabel {
            get {
                return ResourceManager.GetString("AnimationToolSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string AnimationToolStep {
            get {
                return ResourceManager.GetString("AnimationToolStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to the last position.
        /// </summary>
        internal static string AnimationToolTransportJumpToEndHint {
            get {
                return ResourceManager.GetString("AnimationToolTransportJumpToEndHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to the first position.
        /// </summary>
        internal static string AnimationToolTransportJumpToStartHint {
            get {
                return ResourceManager.GetString("AnimationToolTransportJumpToStartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback.
        /// </summary>
        internal static string AnimationToolTransportPauseHint {
            get {
                return ResourceManager.GetString("AnimationToolTransportPauseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play from the current position.
        /// </summary>
        internal static string AnimationToolTransportPlayHint {
            get {
                return ResourceManager.GetString("AnimationToolTransportPlayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play in reverse from the current position.
        /// </summary>
        internal static string AnimationToolTransportReverseHint {
            get {
                return ResourceManager.GetString("AnimationToolTransportReverseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth of Cut.
        /// </summary>
        internal static string CutDepth {
            get {
                return ResourceManager.GetString("CutDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting Height.
        /// </summary>
        internal static string CuttingHeight {
            get {
                return ResourceManager.GetString("CuttingHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting Parameters.
        /// </summary>
        internal static string CuttingParameters {
            get {
                return ResourceManager.GetString("CuttingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting Tool Parameters.
        /// </summary>
        internal static string CuttingToolParameters {
            get {
                return ResourceManager.GetString("CuttingToolParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Diameter.
        /// </summary>
        internal static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and edit UV tool paths..
        /// </summary>
        internal static string FaceToolPathToolButtonHint {
            get {
                return ResourceManager.GetString("FaceToolPathToolButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV.
        /// </summary>
        internal static string FaceToolPathToolButtonText {
            get {
                return ResourceManager.GetString("FaceToolPathToolButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///  &lt;panel&gt;
        ///    &lt;group id=&quot;FaceToolPathToolGroup&quot; label=&quot;Profile Options&quot;&gt;
        ///      &lt;container id=&quot;FaceToolPathToolContainer&quot; layoutOrientation=&quot;vertical&quot;&gt;
        ///        &lt;container id=&quot;FaceToolPathToolStrategyContainer&quot; layoutOrientation=&quot;horizontal&quot;&gt;
        ///          &lt;label id=&quot;FaceToolPathToolStrategyLabel&quot; text=&quot;Strategy:&quot; width=&quot;40&quot;/&gt;
        ///          &lt;comboBox id=&quot;FaceToolPathToolStrategyList&quot; command=&quot;FaceToolPathToolStrat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FaceToolPathToolOptions {
            get {
                return ResourceManager.GetString("FaceToolPathToolOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a face to create a tool path, or select a tool path to edit it..
        /// </summary>
        internal static string FaceToolPathToolStatusText {
            get {
                return ResourceManager.GetString("FaceToolPathToolStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Rate.
        /// </summary>
        internal static string FeedRate {
            get {
                return ResourceManager.GetString("FeedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Feed Rate.
        /// </summary>
        internal static string FeedRateRapid {
            get {
                return ResourceManager.GetString("FeedRateRapid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Length.
        /// </summary>
        internal static string Increment {
            get {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Clearance Height.
        /// </summary>
        internal static string RestZ {
            get {
                return ResourceManager.GetString("RestZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Over.
        /// </summary>
        internal static string StepOver {
            get {
                return ResourceManager.GetString("StepOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAM.
        /// </summary>
        internal static string TabText {
            get {
                return ResourceManager.GetString("TabText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ToolPath32 {
            get {
                object obj = ResourceManager.GetObject("ToolPath32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiral.
        /// </summary>
        internal static string ToolPathFaceSpiral {
            get {
                return ResourceManager.GetString("ToolPathFaceSpiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV Cutline.
        /// </summary>
        internal static string ToolPathFaceUV {
            get {
                return ResourceManager.GetString("ToolPathFaceUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Path.
        /// </summary>
        internal static string ToolPathGroupText {
            get {
                return ResourceManager.GetString("ToolPathGroupText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TransportBackToBeginning {
            get {
                object obj = ResourceManager.GetObject("TransportBackToBeginning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransportFastForward {
            get {
                object obj = ResourceManager.GetObject("TransportFastForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransportForwardToEnd {
            get {
                object obj = ResourceManager.GetObject("TransportForwardToEnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransportLoop {
            get {
                object obj = ResourceManager.GetObject("TransportLoop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransportPause {
            get {
                object obj = ResourceManager.GetObject("TransportPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransportPlay {
            get {
                object obj = ResourceManager.GetObject("TransportPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransportReverse {
            get {
                object obj = ResourceManager.GetObject("TransportReverse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransportRewind {
            get {
                object obj = ResourceManager.GetObject("TransportRewind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransportStop {
            get {
                object obj = ResourceManager.GetObject("TransportStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UVToolPath {
            get {
                object obj = ResourceManager.GetObject("UVToolPath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UVToolPathDisabled {
            get {
                object obj = ResourceManager.GetObject("UVToolPathDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        internal static string Vizualization {
            get {
                return ResourceManager.GetString("Vizualization", resourceCulture);
            }
        }
    }
}
