//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAM.
        /// </summary>
        internal static string TabText {
            get {
                return ResourceManager.GetString("TabText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ToolPath32 {
            get {
                object obj = ResourceManager.GetObject("ToolPath32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Path.
        /// </summary>
        internal static string ToolPathGroupText {
            get {
                return ResourceManager.GetString("ToolPathGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UVPathName {
            get {
                return ResourceManager.GetString("UVPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string UVPathToolAnimationPause {
            get {
                return ResourceManager.GetString("UVPathToolAnimationPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string UVPathToolAnimationPlay {
            get {
                return ResourceManager.GetString("UVPathToolAnimationPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string UVPathToolAnimationStep {
            get {
                return ResourceManager.GetString("UVPathToolAnimationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and edit UV tool paths..
        /// </summary>
        internal static string UVPathToolButtonHint {
            get {
                return ResourceManager.GetString("UVPathToolButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV.
        /// </summary>
        internal static string UVPathToolButtonText {
            get {
                return ResourceManager.GetString("UVPathToolButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///	&lt;panel&gt;
        ///		&lt;group id=&quot;UVPathToolGroup&quot; label=&quot;Profile Options&quot;&gt;
        ///			&lt;container id=&quot;UVPathToolContainer&quot; layoutOrientation=&quot;vertical&quot;&gt;
        ///				&lt;container id=&quot;UVPathToolContainerColor&quot; layoutOrientation=&quot;horizontal&quot;&gt;
        ///					&lt;label id=&quot;UVPathToolColorLabel&quot; text=&quot;Color:&quot; width=&quot;40&quot;/&gt;
        ///
        ///					&lt;!--
        ///						Combo box items can either be specified in XML, or specified by setting the Command.ControlState to
        ///						be a C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UVPathToolOptions {
            get {
                return ResourceManager.GetString("UVPathToolOptions", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UVToolPath {
            get {
                object obj = ResourceManager.GetObject("UVToolPath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UVToolPathDisabled {
            get {
                object obj = ResourceManager.GetObject("UVToolPathDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
