//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discrete.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Discrete.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        internal static string AnnotationLayerName {
            get {
                return ResourceManager.GetString("AnnotationLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane.
        /// </summary>
        internal static string AnnotationPlaneName {
            get {
                return ResourceManager.GetString("AnnotationPlaneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Planes.
        /// </summary>
        internal static string AnnotationPlanesLayerName {
            get {
                return ResourceManager.GetString("AnnotationPlanesLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate the 3-fold Boy surface, a projective plane embedded in R3..
        /// </summary>
        internal static string BoyToolHint {
            get {
                return ResourceManager.GetString("BoyToolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy Tool.
        /// </summary>
        internal static string BoyToolText {
            get {
                return ResourceManager.GetString("BoyToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates curve copies of the edges of selected faces, removing duplicate edges..
        /// </summary>
        internal static string CopyCurvesHint {
            get {
                return ResourceManager.GetString("CopyCurvesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Curves.
        /// </summary>
        internal static string CopyCurvesText {
            get {
                return ResourceManager.GetString("CopyCurvesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forget what this does..
        /// </summary>
        internal static string CreateAnimateCommandHint {
            get {
                return ResourceManager.GetString("CreateAnimateCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate.
        /// </summary>
        internal static string CreateAnimateCommandText {
            get {
                return ResourceManager.GetString("CreateAnimateCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Dashes.
        /// </summary>
        internal static string CreateDashesText {
            get {
                return ResourceManager.GetString("CreateDashesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a figure 8 Kein bottle..
        /// </summary>
        internal static string CreateFigure8CommandHint {
            get {
                return ResourceManager.GetString("CreateFigure8CommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure 8.
        /// </summary>
        internal static string CreateFigure8CommandText {
            get {
                return ResourceManager.GetString("CreateFigure8CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Poincare Disk..
        /// </summary>
        internal static string CreatePoincareDiskCommandHint {
            get {
                return ResourceManager.GetString("CreatePoincareDiskCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poincare Disk.
        /// </summary>
        internal static string CreatePoincareDiskCommandText {
            get {
                return ResourceManager.GetString("CreatePoincareDiskCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Collisions.
        /// </summary>
        internal static string DetectCollisionsText {
            get {
                return ResourceManager.GetString("DetectCollisionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete.
        /// </summary>
        internal static string DiscreteTabText {
            get {
                return ResourceManager.GetString("DiscreteTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string EdgeOffsetFieldText {
            get {
                return ResourceManager.GetString("EdgeOffsetFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a single tab on the end of an edge strip..
        /// </summary>
        internal static string EdgeTabHint {
            get {
                return ResourceManager.GetString("EdgeTabHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab on Edge.
        /// </summary>
        internal static string EdgeTabText {
            get {
                return ResourceManager.GetString("EdgeTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record the angle between the endpoints of the selected curves..
        /// </summary>
        internal static string ExcelAngleHint {
            get {
                return ResourceManager.GetString("ExcelAngleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string ExcelAngleText {
            get {
                return ResourceManager.GetString("ExcelAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        internal static string ExcelGroupText {
            get {
                return ResourceManager.GetString("ExcelGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record the length of the selected curves..
        /// </summary>
        internal static string ExcelLengthHint {
            get {
                return ResourceManager.GetString("ExcelLengthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string ExcelLengthText {
            get {
                return ResourceManager.GetString("ExcelLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to cell A1..
        /// </summary>
        internal static string ExcelResetHint {
            get {
                return ResourceManager.GetString("ExcelResetHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ExcelResetText {
            get {
                return ResourceManager.GetString("ExcelResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting Lines.
        /// </summary>
        internal static string FlatCuttingLinesLayerName {
            get {
                return ResourceManager.GetString("FlatCuttingLinesLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Bodies.
        /// </summary>
        internal static string FlatFaceLayerName {
            get {
                return ResourceManager.GetString("FlatFaceLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Face.
        /// </summary>
        internal static string FlatFaceName {
            get {
                return ResourceManager.GetString("FlatFaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Engraving.
        /// </summary>
        internal static string FlatMediumEngravingLayerName {
            get {
                return ResourceManager.GetString("FlatMediumEngravingLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip the side of the curve on which the Tabs are created..
        /// </summary>
        internal static string FlipTabsHint {
            get {
                return ResourceManager.GetString("FlipTabsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Tabs.
        /// </summary>
        internal static string FlipTabsText {
            get {
                return ResourceManager.GetString("FlipTabsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyroid.
        /// </summary>
        internal static string GyroidGroupText {
            get {
                return ResourceManager.GetString("GyroidGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts to relax to the gyroid minimal surface..
        /// </summary>
        internal static string GyroidRelaxHint {
            get {
                return ResourceManager.GetString("GyroidRelaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string GyroidRelaxText {
            get {
                return ResourceManager.GetString("GyroidRelaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat Lawson circle..
        /// </summary>
        internal static string LawsonCircleCommandHint {
            get {
                return ResourceManager.GetString("LawsonCircleCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawson Circle.
        /// </summary>
        internal static string LawsonCircleCommandText {
            get {
                return ResourceManager.GetString("LawsonCircleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Lawson Klein bottle..
        /// </summary>
        internal static string LawsonCreateCommandHint {
            get {
                return ResourceManager.GetString("LawsonCreateCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawson.
        /// </summary>
        internal static string LawsonCreateCommandText {
            get {
                return ResourceManager.GetString("LawsonCreateCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relax Lawson Tabs.
        /// </summary>
        internal static string LawsonRelaxHint {
            get {
                return ResourceManager.GetString("LawsonRelaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relax.
        /// </summary>
        internal static string LawsonRelaxText {
            get {
                return ResourceManager.GetString("LawsonRelaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Average.
        /// </summary>
        internal static string LawsonTabAngleAverageForce {
            get {
                return ResourceManager.GetString("LawsonTabAngleAverageForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Angle.
        /// </summary>
        internal static string LawsonTabAngleForce {
            get {
                return ResourceManager.GetString("LawsonTabAngleForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ready for the zany Lawson Tool..
        /// </summary>
        internal static string LawsonToolHint {
            get {
                return ResourceManager.GetString("LawsonToolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust.
        /// </summary>
        internal static string LawsonToolText {
            get {
                return ResourceManager.GetString("LawsonToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U Angle.
        /// </summary>
        internal static string LawsonUAngleForce {
            get {
                return ResourceManager.GetString("LawsonUAngleForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U Touch.
        /// </summary>
        internal static string LawsonUTouchForce {
            get {
                return ResourceManager.GetString("LawsonUTouchForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V Align.
        /// </summary>
        internal static string LawsonVAlignmentForce {
            get {
                return ResourceManager.GetString("LawsonVAlignmentForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V Average.
        /// </summary>
        internal static string LawsonVAverageForce {
            get {
                return ResourceManager.GetString("LawsonVAverageForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenticular.
        /// </summary>
        internal static string Lenticular {
            get {
                return ResourceManager.GetString("Lenticular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a cylindrical lenticular thingie..
        /// </summary>
        internal static string LenticularCylindricalCommandHint {
            get {
                return ResourceManager.GetString("LenticularCylindricalCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindrical.
        /// </summary>
        internal static string LenticularCylindricalCommandText {
            get {
                return ResourceManager.GetString("LenticularCylindricalCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlace Slices.
        /// </summary>
        internal static string LenticularInterlaceCount {
            get {
                return ResourceManager.GetString("LenticularInterlaceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlace Width.
        /// </summary>
        internal static string LenticularInterlaceWidth {
            get {
                return ResourceManager.GetString("LenticularInterlaceWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planar.
        /// </summary>
        internal static string LenticularPlanar {
            get {
                return ResourceManager.GetString("LenticularPlanar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create planar lenticular image..
        /// </summary>
        internal static string LenticularPlanarCommandHint {
            get {
                return ResourceManager.GetString("LenticularPlanarCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planar.
        /// </summary>
        internal static string LenticularPlanarCommandText {
            get {
                return ResourceManager.GetString("LenticularPlanarCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweep Angle.
        /// </summary>
        internal static string LenticularSweepAngle {
            get {
                return ResourceManager.GetString("LenticularSweepAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tabs to a chain of curve segments..
        /// </summary>
        internal static string MakeTabsHint {
            get {
                return ResourceManager.GetString("MakeTabsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Tabs.
        /// </summary>
        internal static string MakeTabsText {
            get {
                return ResourceManager.GetString("MakeTabsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset edges in the direction of the average normal..
        /// </summary>
        internal static string OffsetEdgesHint {
            get {
                return ResourceManager.GetString("OffsetEdgesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Edges.
        /// </summary>
        internal static string OffsetEdgesText {
            get {
                return ResourceManager.GetString("OffsetEdgesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedural.
        /// </summary>
        internal static string ProceduralGroupText {
            get {
                return ResourceManager.GetString("ProceduralGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Start with a slot rather than with a tab..
        /// </summary>
        internal static string StartSlotHint {
            get {
                return ResourceManager.GetString("StartSlotHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Slot.
        /// </summary>
        internal static string StartSlotText {
            get {
                return ResourceManager.GetString("StartSlotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        internal static string TabGroupText {
            get {
                return ResourceManager.GetString("TabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        internal static string TabsGroupText {
            get {
                return ResourceManager.GetString("TabsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnfoldMore.
        /// </summary>
        internal static string TabText {
            get {
                return ResourceManager.GetString("TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilf.
        /// </summary>
        internal static string WilfGroupText {
            get {
                return ResourceManager.GetString("WilfGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Herb Wilf&apos;s Tree..
        /// </summary>
        internal static string WilfHint {
            get {
                return ResourceManager.GetString("WilfHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilf.
        /// </summary>
        internal static string WilfText {
            get {
                return ResourceManager.GetString("WilfText", resourceCulture);
            }
        }
    }
}
