//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Animator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move a component sinusoidally..
        /// </summary>
        internal static string OscillatorToolHint {
            get {
                return ResourceManager.GetString("OscillatorToolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscillator.
        /// </summary>
        internal static string OscillatorToolText {
            get {
                return ResourceManager.GetString("OscillatorToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording a new movie..
        /// </summary>
        internal static string RecordMovieHint {
            get {
                return ResourceManager.GetString("RecordMovieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string RecordMovieText {
            get {
                return ResourceManager.GetString("RecordMovieText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///	&lt;ribbon&gt;
        ///		&lt;tabs&gt;
        ///			&lt;tab id=&quot;AnimatorTab&quot; label=&quot;Animator&quot;&gt;
        ///        &lt;group id=&quot;AnimatorTransportGroup&quot; label=&quot;Transport&quot; layoutOrientation=&quot;horizontal&quot; itemSpacing=&quot;1&quot;&gt;
        ///            &lt;button id=&quot;Animator.Play&quot; size=&quot;large&quot; command=&quot;Animator.Play&quot; /&gt;
        ///            &lt;button id=&quot;Animator.Reset&quot; size=&quot;large&quot; command=&quot;Animator.Reset&quot; /&gt;
        ///        &lt;/group&gt;
        ///        &lt;group id=&quot;AnimatorToolGroup&quot; label=&quot;Transport&quot; la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
    }
}
